### ISSUE TITLE
Top level main.css is not respected

### ISSUE THREAD

**Issue by JamesMilnerUK** [dojo/cli-build-app#104]
When you have an app with a top level main.css file, the corresponding CSS classes not applied to target elements: 

![spectacle ab5948](https://user-images.githubusercontent.com/8822075/41416645-45b21a2e-6fe3-11e8-9ed2-518f681b2b19.png)

```javascript

class App extends WidgetBase {
	protected render() {
		return v('div',  { classes: css.test }, ["Hello World"])
	}
}

```

```css
html, body  {
	height: 100%;
	width: 100%;
	margin: 0px;
}

.test {
	color: red;
}
```

The CSS type definition appears to be created correctly:

```
export const test: string;
```
